<?php

use Omeka\Api\Representation\SitePageBlockRepresentation;
use Omeka\Api\Representation\SitePageRepresentation;

/**
 * @var SitePageRepresentation $page
 * @var SitePageBlockRepresentation $block
 */

$layouts = [];
foreach ($page->blocks() as $block):

    if (!array_key_exists($block->layout(), $layouts)) {
        // Prepare render only once per layout type.
        $layouts[$block->layout()] = null;
        $this->blockLayout()->prepareRender($block->layout());
    }

//    print_r($block->dataValue('divclass', 'section--default'));
//    print_r($block->data());
    $sectionClass = "block block--{$block->layout()} ".($block->dataValue('divclass', '') ?: 'block--default');
    ?>
    <div class="<?= $sectionClass ?>">
        <div class="container">
                <?= $this->blockLayout()->render($block); ?>
        </div>
    </div>
<?php endforeach; ?>
