<?php

use Omeka\Api\Representation\SitePageBlockRepresentation;
use Omeka\Api\Representation\SitePageRepresentation;

/**
 * @var SitePageRepresentation $page
 * @var SitePageBlockRepresentation $block
 */

function _templateToCamel($input)
{
    return lcfirst(str_replace(' ', '', ucwords(str_replace('-', ' ', $input))));
}

$layouts = [];
foreach ($page->blocks() as $block):

    // prepare render of block (only once)
    if (!array_key_exists($block->layout(), $layouts)) {
        $layouts[$block->layout()] = null;
        $this->blockLayout()->prepareRender($block->layout());
    }

    $blockLayout = $block->layout();
    $blockLayout = str_replace(['itemShowCase'], ['itemShowcase'], $blockLayout); // fix
    $blockLayoutClass = strtolower(preg_replace('/([A-Z]+)/', '-${1}', $blockLayout));

    // default block classes
    $blockClasses = [
            "block-wrapper",
            "block--{$blockLayoutClass}"
    ];
    // add custom class
    if ( $divclass = $block->dataValue('divclass', null) ) {
        $blockClasses[] = $divclass;
    }
    // add class based on template name
    if ( $template = $block->dataValue('template', null) ) {
        $template = array_reverse(explode(DIRECTORY_SEPARATOR, $template))[0];
        $templateClass = str_replace(' ', '-', $template);
        $templateClass = ltrim(str_replace($blockLayoutClass, '', $templateClass),'- '); // todo: this is incorrect, default template can differ from block layout name
        $blockClasses[] = "block--{$blockLayoutClass}--{$templateClass}";
    } else {
        $template = 'default';
    }

    $blockClasses = implode(' ', $blockClasses);

    $containerClasses = ['block-container'];
    $containerClasses = implode(' ', $containerClasses);

    // render
    ?>
    <section class="<?= $blockClasses ?>" data-block-template="<?= $template ?>" data-block-id="<?= $block->id() ?>">
        <div class="<?= $containerClasses ?>">
            <?= $this->blockLayout()->render($block); ?>
        </div>
    </section>
<?php endforeach; ?>
