<?php
/**
 * @var \Laminas\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\SitePageBlockRepresentation $block
 * @var \Omeka\Api\Representation\SiteBlockAttachmentRepresentation[] $attachments
 * @var string $heading
 * @var string $html
 * @var string $alignmentClass "left" or "right"
 * @var string $thumbnailType
 * @var string $showTitleOption "item_title" or "file_name" or "none".
 * @var string $captionPosition "center", "left" or "right".
 */

$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$siteSetting = $this->plugin('siteSetting');
$thumbnail = $this->plugin('thumbnail');

$linkType = $siteSetting('attachment_link_type', 'item');

$filterLocale = (bool) $this->siteSetting('filter_locale_values');
$lang = $filterLocale ? $this->lang() : null;

$classMedia = $classMedia ?? "media file col-xs-12 col-lg-6";
$classText = $classText ?? "text col-xs-12 col-lg-6";
$classContainer = $classContainer ?? "row";
?>

<div class="block media-text">
    <?php if (!empty($heading)): ?>
    <header>
        <h2><?= $escape($heading) ?></h2>
    </header>
    <?php endif; ?>
    <article class="<?= $classContainer ?>">
        <div class="<?= $classMedia ?> <?= $alignmentClass . ' ' . $thumbnailType . ' captions-' . $captionPosition ?>">
            <div class="attachments">
                <?php
                foreach ($attachments as $attachment):
                    $render = null;
                    $title = null;
                    $link = null;
                    $item = $attachment->item();
                    if ($item):
                        $media = $attachment->media() ?: $item->primaryMedia();
                        if ($media):
                            // prefer to render thumbnail (avoid openseadragon)
                            if ($media->hasThumbnails()) {
                                $render = $thumbnail($media, $thumbnailType);
                            } else {
                                $render = $media->render([
                                    'thumbnailType' => $thumbnailType,
                                    'link' => $linkType,
                                ]);
                            }
                        endif;

                        if ($showTitleOption == 'item_title'):
                            $title = $item->displayTitle(null, $lang);
                        elseif ($media && $showTitleOption == 'file_name'):
                            $title = $media->displayTitle(null, $lang);
                        endif;

                        if ($title):
                            if ($media && $linkType === 'media'):
                                $link = $media->link($title);
                            elseif ($media && $linkType === 'original' && $media->hasOriginal()):
                                $link = $hyperlink($title, $media->originalUrl());
                            else:
                                $link = $item->link($title);
                            endif;
                        endif;
                    endif;

                    $caption = $attachment->caption();
                ?>
                <div class="item resource">
                    <?= $render ?>
                    <?= $link ?>
                    <div class="caption">
                        <?= $caption ?>
                    </div>
                </div>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="<?= $classText ?>">
            <?= $html ?>
        </div>
    </article>
</div>
