<?php
/**
 * @var $site Omeka\Api\Representation\SiteRepresentation
 */
$boolIsProduction = ($_SERVER['APPLICATION_ENV'] ?? 'production') !== 'development';

$escape = $this->plugin('escapeHtml');
$userBar = $this->userBar();

$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');

// favicon
$this->headLink(['rel' => 'icon', 'href' => $this->assetUrl('favicon/icon.ico'), 'sizes' => 'any']);
$this->headLink(['rel' => 'icon', 'href' => $this->assetUrl('favicon/icon.svg'), 'type' => 'image/svg+xml']);
$this->headLink(['rel' => 'apple-touch-icon', 'href' => $this->assetUrl('favicon/apple-touch-icon.png'), 'sizes' => 'any']);

// css
if ( $boolIsProduction ) {
    $this->headLink()->appendStylesheet($this->assetUrl('css/main.css'));
}
// js
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

if ( $boolIsProduction ) {
//    $this->headScript()->prependFile($this->assetUrl('js/main.js'), 'text/javascript', ['type' => 'module']); //, ['defer' => true]);
//    $this->headScript()->prependFile($this->assetUrl('js/main.js'), 'text/javascript', ['type' => 'module']); //, ['defer' => true]);
    $this->headScript()->prependFile('https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js', 'text/javascript');
    $this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
/*
 * <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
 * <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
 *
 */
} else {
    $this->headScript()->prependFile('http://localhost:5173/@vite/client', 'text/javascript', ['type' => 'module']);
    $this->headScript()->prependFile('http://localhost:5173/js/main.js', 'text/javascript', ['type' => 'module']);
    $this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
}
$this->headScript()->setAllowArbitraryAttributes(true);
$this->jsTranslate();
$this->trigger('view.layout');

// split menu container in left and right container
$navigationFirst = new Laminas\Navigation\Navigation();
$navigationLeft = new Laminas\Navigation\Navigation();
$navigationRight = new Laminas\Navigation\Navigation();
$navigationPages = $site->publicNav()->menu()->getContainer()->getPages();

$countPages = count($navigationPages);

$i = 0;
foreach($navigationPages as $item ) {
    $i++;
    $item->setClass('nav-link');
    if ( $i == 1 ) {
        $navigationFirst->addPage($item);
        continue;
    }
    if ( $i > ceil($countPages/2) ) {
        $navigationRight->addPage($item);
    } else {
        $navigationLeft->addPage($item);
    }
}
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>

            <header>
                <?= $userBar ?>
                <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
                    <div class="navbar-brand">
                        <div class="navbar-brand-border-left"></div>
                        <div class="navbar-brand-image">
                            <a href="<?= $site->url(null, true) ?>">
                                <img src="<?= $this->assetUrl("images/logo-white.svg"); ?>" alt="Gent Gemapt">
                            </a>
                        </div>
                        <div class="navbar-brand-border-right"></div>
                    </div>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="container-xl">
                        <div class="row w-100">
                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <div class="navbar-container-left">
                                    <?= $site->publicNav()->menu()->renderPartialWithParams(['navContainerClass' => 'navbar-nav navbar-nav--first'], $navigationFirst, 'navigation/topnav.phtml'); ?>
                                    <?= $site->publicNav()->menu()->renderPartialWithParams(['navContainerClass' => 'navbar-nav navbar-nav--left'], $navigationLeft, 'navigation/topnav.phtml'); ?>
                                </div>
                                <div class="navbar-container-right">
                                    <?= $site->publicNav()->menu()->renderPartialWithParams(['navContainerClass' => 'navbar-nav navbar-nav--right ms-auto'], $navigationRight, 'navigation/topnav.phtml'); ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </nav>
            </header>

            <main class="container-xl">
                <div class="row w-100">
                    <?php echo $this->content; ?>
                </div>
            </main>

            <footer class="container-xl">
                <div class="row w-100">
                        <?php if ($footerContent = $this->themeSetting('footer')): ?>
                            <?= str_replace('{assetPrefix}', $this->assetUrl('',null, false, false), $footerContent); ?>
                        <?php endif; ?>
                        <div class="sections">
                            <div class="section">
                                <div class="container">
                                    <div class="footer__logos">
                                        <div>
                                            <a href="" target="_blank">
                                                <img src="<?= $this->assetUrl("images/logo/logo_vlaanderen.svg"); ?>" alt="Logo Vlaanderen - Verbeelding werkt">
                                            </a>
                                        </div>
                                        <div>
                                            <a href="https://ugent.be" target="_blank">
                                                <img src="<?= $this->assetUrl("images/logo/logo_ugent_nl_kleur.svg"); ?>" alt="Logo Universiteit Gent">
                                            </a>
                                        </div>
                                        <div>
                                            <a href="" target="_blank">
                                                <img src="<?= $this->assetUrl("images/logo/logo_clariah_vl.png"); ?>" alt="Logo Clariah-Vl">
                                            </a>
                                        </div>
                                        <div>
                                            <a href="https://gent.be" target="_blank">
                                                <img src="<?= $this->assetUrl("images/logo/logo_stad_gent.svg"); ?>" alt="Logo Stad Gent">
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="section">
                                <div class="container">
                                    <div class="footer__text">
                                        Gent Gemapt is een platform van de Boekentoren, Archief Gent, Erfgoedcel Gent, Stam Gent, Huis van Alijn, Industriemuseum, Amsab - Instituut voor Sociale Geschiedenis, Liberas en het Ghent Center for Digital Humanities van de UGent.
                                    </div>
                                </div>
                            </div>

                        </div>
                    </div>
            </footer>
            <footer class="container-fluid bg-blue">
                <div class="container-xl">
                    <div class="row w-100 sections">
                        <div class="section section--compact">
                            <div class="w-100">
                                <div class="footer__text">
                                    © GentGemapt, 2023 - gebouwd door het Ghent Center for Digital Humanities.
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
    </body>
</html>
