<?php
/**
 * @var $site Omeka\Api\Representation\SiteRepresentation
 */
$boolIsProduction = $_SERVER['APPLICATION_ENV'] !== 'development';

$escape = $this->plugin('escapeHtml');
$userBar = $this->userBar();

$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');

// favicon
$this->headLink(['rel' => 'icon', 'href' => $this->assetUrl('favicon/icon.ico'), 'sizes' => 'any']);
$this->headLink(['rel' => 'icon', 'href' => $this->assetUrl('favicon/icon.svg'), 'type' => 'image/svg+xml']);
$this->headLink(['apple-touch-icon' => 'icon', 'href' => $this->assetUrl('favicon/icon.ico'), 'sizes' => 'any']);

// css
if ( $boolIsProduction ) {
    $this->headLink()->appendStylesheet($this->assetUrl('build/index.css'));
}
// js
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));

if ( $boolIsProduction ) {
    $this->headScript()->prependFile($this->assetUrl('build/index.js'), 'text/javascript'); //, ['defer' => true]);
} else {
    $this->headScript()->prependFile('http://localhost:5173/@vite/client', 'text/javascript', ['type' => 'module']);
    $this->headScript()->prependFile('http://localhost:5173/js/main.js', 'text/javascript', ['type' => 'module']);   
}
$this->headScript()->setAllowArbitraryAttributes(true);
$this->jsTranslate();
$this->trigger('view.layout');


// split menu container in left and right container
$navigationFirst = new Laminas\Navigation\Navigation();
$navigationLeft = new Laminas\Navigation\Navigation();
$navigationRight = new Laminas\Navigation\Navigation();
$navigationPages = $site->publicNav()->menu()->getContainer()->getPages();

$countPages = count($navigationPages);

$i = 0;
foreach($navigationPages as $item ) {
    $i++;
    $item->setClass('nav-link');
    if ( $i == 1 ) {
        $navigationFirst->addPage($item);
        continue;
    }
    if ( $i > ceil($countPages/2) ) {
        $navigationRight->addPage($item);
    } else {
        $navigationLeft->addPage($item);
    }
}
?>


<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <div class="container-xl">
            <header>
                <?= $userBar ?>
                <nav class="navbar navbar-dark bg-dark navbar-expand-lg">
                    <div class="navbar-brand">
                        <div class="navbar-brand-border-left"></div>
                        <div class="navbar-brand-image">
                            <a href="<?= $site->url() ?>">
                                <img src="<?= $this->assetUrl("images/logo-white.svg"); ?>" alt="Gent Gemapt">
                            </a>
                        </div>
                        <div class="navbar-brand-border-right"></div>
                    </div>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <div class="navbar-container-left">
                            <?= $site->publicNav()->menu()->renderPartialWithParams(['navContainerClass' => 'navbar-nav navbar-nav--first'], $navigationFirst, 'navigation/topnav.phtml'); ?>
                            <?= $site->publicNav()->menu()->renderPartialWithParams(['navContainerClass' => 'navbar-nav navbar-nav--left'], $navigationLeft, 'navigation/topnav.phtml'); ?>
                        </div>
                        <div class="navbar-container-right">
                            <?= $site->publicNav()->menu()->renderPartialWithParams(['navContainerClass' => 'navbar-nav navbar-nav--right ms-auto'], $navigationRight, 'navigation/topnav.phtml'); ?>
                        </div>
                    </div>
                </nav>
            </header>

            <main>
                <?php echo $this->content; ?>
            </main>

            <footer>
                © Ghent Centre for Digital Humanities
            </footer>
        </div>
    </body>
</html>
